import type { ThunderstorePackage } from "../../src/lib/types";

/**
 * Curated package fixture for README screenshots. A trimmed snapshot of real
 * Thunderstore Valheim listings; only the fields the browse grid renders are
 * kept. Download counts are cumulative (all versions), like the backend sends
 * them, and are rounded to plausible totals.
 */
const PACKAGES_RAW: ThunderstorePackage[] = [
  {
    name: "Jotunn",
    full_name: "ValheimModding-Jotunn",
    owner: "ValheimModding",
    package_url: "https://thunderstore.io/c/valheim/p/ValheimModding/Jotunn/",
    description:
      "Jötunn (/ˈjɔːtʊn/, 'giant'), the Valheim Library was created with the goal of making the lives of mod developers easier. It enables you to create mods for Valheim using an abstrac…",
    version_number: "2.30.2",
    rating_score: 347,
    downloads: 17800000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/ValheimModding-Jotunn-2.30.2.png",
    categories: ["Libraries", "Deep North Update"],
    date_updated: "2026-09-26T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "PlantEverything",
    full_name: "Advize-PlantEverything",
    owner: "Advize",
    package_url: "https://thunderstore.io/c/valheim/p/Advize/PlantEverything/",
    description:
      "Allows your cultivator to plant berry bushes, thistle, dandelions, mushrooms, previously unavailable tree types, and other decorative flora. Includes many other miscellaneous feat…",
    version_number: "1.21.3",
    rating_score: 428,
    downloads: 12600000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Advize-PlantEverything-1.21.3.png",
    categories: ["Mods", "Server-side", "Client-side", "Deep North Update"],
    date_updated: "2026-09-22T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "EquipmentAndQuickSlots",
    full_name: "RandyKnapp-EquipmentAndQuickSlots",
    owner: "RandyKnapp",
    package_url: "https://thunderstore.io/c/valheim/p/RandyKnapp/EquipmentAndQuickSlots/",
    description:
      "Give equipped items their own dedicated inventory slots, plus up to six hotkeyable quick slots.",
    version_number: "3.1.3",
    rating_score: 316,
    downloads: 9400000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/RandyKnapp-EquipmentAndQuickSlots-3.1.3.png",
    categories: [
      "Client-side",
      "Tweaks",
      "Ashlands Update",
      "Mistlands Update",
      "Utility",
      "Bog Witch Update",
      "Deep North Update",
    ],
    date_updated: "2026-09-18T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "TeleportEverything",
    full_name: "OdinPlus-TeleportEverything",
    owner: "OdinPlus",
    package_url: "https://thunderstore.io/c/valheim/p/OdinPlus/TeleportEverything/",
    description:
      "This mod adds extra excitement and functionality to the portal system. Teleport wolves, boars, loxes and other allies. Transport ores, ingots, carts and even take enemies with you…",
    version_number: "2.9.1",
    rating_score: 130,
    downloads: 8200000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/OdinPlus-TeleportEverything-2.9.1.png",
    categories: [
      "Transportation",
      "Server-side",
      "Client-side",
      "Hildir's Request Update",
      "Ashlands Update",
      "Mistlands Update",
      "Utility",
      "Bog Witch Update",
      "Mods",
    ],
    date_updated: "2026-09-14T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "ConfigurationManager",
    full_name: "shudnal-ConfigurationManager",
    owner: "shudnal",
    package_url: "https://thunderstore.io/c/valheim/p/shudnal/ConfigurationManager/",
    description:
      "Localized, recolored, refined. Split view mode. Config files editor. Setting edit window. Changed values are highlighted. Prevent user input or pause the game while window is open…",
    version_number: "1.1.22",
    rating_score: 130,
    downloads: 7100000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/shudnal-ConfigurationManager-1.1.22.png",
    categories: ["Server-side", "Client-side", "Deep North Update", "Utility", "Tools"],
    date_updated: "2026-09-09T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "MultiUserChest",
    full_name: "MSchmoecker-MultiUserChest",
    owner: "MSchmoecker",
    package_url: "https://thunderstore.io/c/valheim/p/MSchmoecker/MultiUserChest/",
    description: "Allows multiple players to interact with the same chest at the same time",
    version_number: "0.6.2",
    rating_score: 125,
    downloads: 6300000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/MSchmoecker-MultiUserChest-0.6.2.png",
    categories: ["Server-side", "Client-side", "Deep North Update", "Utility", "Mods"],
    date_updated: "2026-09-03T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "AdventureBackpacks",
    full_name: "Vapok-AdventureBackpacks",
    owner: "Vapok",
    package_url: "https://thunderstore.io/c/valheim/p/Vapok/AdventureBackpacks/",
    description:
      "A Valheim Mod to add a catalogue of Adventuring Backpacks to the Game. These packs will grow and become more useful as the game progresses.",
    version_number: "2.2.2",
    rating_score: 194,
    downloads: 5900000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Vapok-AdventureBackpacks-2.2.2.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Hildir's Request Update",
      "Tools",
      "Ashlands Update",
      "Gear",
      "Utility",
      "Mods",
      "Bog Witch Update",
      "Deep North Update",
    ],
    date_updated: "2026-08-29T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "AzuExtendedPlayerInventory",
    full_name: "Azumatt-AzuExtendedPlayerInventory",
    owner: "Azumatt",
    package_url: "https://thunderstore.io/c/valheim/p/Azumatt/AzuExtendedPlayerInventory/",
    description:
      "AzuEPI (Extended Player Inventory) is a comprehensive inventory expansion mod that adds more rows to inventory, equipment slots, quick slots, vanity customization, and loadout man…",
    version_number: "2.4.14",
    rating_score: 239,
    downloads: 5400000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Azumatt-AzuExtendedPlayerInventory-2.4.14.png",
    categories: [
      "Server-side",
      "Client-side",
      "Hildir's Request Update",
      "Ashlands Update",
      "Mistlands Update",
      "Gear",
      "Utility",
      "Mods",
      "Bog Witch Update",
      "Misc",
    ],
    date_updated: "2026-08-23T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "ServerCharacters",
    full_name: "Smoothbrain-ServerCharacters",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/ServerCharacters/",
    description:
      "Saves your character on the server, instead of your computer, to prevent you from messing with it.",
    version_number: "1.4.16",
    rating_score: 69,
    downloads: 4800000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-ServerCharacters-1.4.16.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Bog Witch Update",
      "Mods",
      "Misc",
      "Libraries",
    ],
    date_updated: "2026-08-16T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Blacksmiths_tools",
    full_name: "GoldenJude-Blacksmiths_tools",
    owner: "GoldenJude",
    package_url: "https://thunderstore.io/c/valheim/p/GoldenJude/Blacksmiths_tools/",
    description:
      "Tool for hiding parts of the player model when equipping wearables, also a fix for incorrectly deforming skinned meshes on custom items.",
    version_number: "3.0.0",
    rating_score: 27,
    downloads: 4200000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/GoldenJude-Blacksmiths_tools-3.0.0.png",
    categories: ["Mods", "Tools", "Client-side", "Deep North Update"],
    date_updated: "2026-08-10T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "HookGenPatcher",
    full_name: "ValheimModding-HookGenPatcher",
    owner: "ValheimModding",
    package_url: "https://thunderstore.io/c/valheim/p/ValheimModding/HookGenPatcher/",
    description:
      "Generates MonoMod.RuntimeDetour.HookGen's MMHOOK file during the BepInEx preloader phase.",
    version_number: "0.0.4",
    rating_score: 56,
    downloads: 3900000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/ValheimModding-HookGenPatcher-0.0.4.png",
    categories: [],
    date_updated: "2026-08-03T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "UnityExplorer",
    full_name: "sinai-dev-UnityExplorer",
    owner: "sinai-dev",
    package_url: "https://thunderstore.io/c/valheim/p/sinai-dev/UnityExplorer/",
    description: "An in-game UI for exploring, debugging and modifying Unity games.",
    version_number: "4.8.2",
    rating_score: 92,
    downloads: 3600000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/sinai-dev-UnityExplorer-4.8.2.png",
    categories: [],
    date_updated: "2026-07-27T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "AutoRepair",
    full_name: "Tekla-AutoRepair",
    owner: "Tekla",
    package_url: "https://thunderstore.io/c/valheim/p/Tekla/AutoRepair/",
    description: "Interacting with a workbench will repair all items it can from your inventory.",
    version_number: "5.4.1602",
    rating_score: 119,
    downloads: 3400000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Tekla-AutoRepair-5.4.1602.png",
    categories: ["Mods", "Crafting"],
    date_updated: "2026-07-20T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "ItemStacks",
    full_name: "mtnewton-ItemStacks",
    owner: "mtnewton",
    package_url: "https://thunderstore.io/c/valheim/p/mtnewton/ItemStacks/",
    description: "Increases item stack size and reduces item weight. Configurable",
    version_number: "1.2.0",
    rating_score: 69,
    downloads: 3100000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/mtnewton-ItemStacks-1.2.0.png",
    categories: ["Mods"],
    date_updated: "2026-07-12T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "UseEquipmentInWater",
    full_name: "LVH-IT-UseEquipmentInWater",
    owner: "LVH-IT",
    package_url: "https://thunderstore.io/c/valheim/p/LVH-IT/UseEquipmentInWater/",
    description: "Allows you to use your Equipment while swimming in water",
    version_number: "0.2.4",
    rating_score: 119,
    downloads: 2900000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/LVH-IT-UseEquipmentInWater-0.2.4.png",
    categories: ["Building", "Misc", "Client-side", "Utility"],
    date_updated: "2026-07-05T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "TrashItems",
    full_name: "virtuaCode-TrashItems",
    owner: "virtuaCode",
    package_url: "https://thunderstore.io/c/valheim/p/virtuaCode/TrashItems/",
    description:
      "This mod adds a trash can to your inventory screen where you can drag and drop your unneeded items to destroy them permanently. (With gamepad support)",
    version_number: "1.2.8",
    rating_score: 93,
    downloads: 2700000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/virtuaCode-TrashItems-1.2.8.png",
    categories: ["Misc", "Client-side", "Utility"],
    date_updated: "2026-06-27T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "TorchesEternal",
    full_name: "Xenofell-TorchesEternal",
    owner: "Xenofell",
    package_url: "https://thunderstore.io/c/valheim/p/Xenofell/TorchesEternal/",
    description:
      "Torches and other fire sources that require fuel (campfire, hearth, etc) will burn infinitely when using Torches Eternal.",
    version_number: "0.2.0",
    rating_score: 48,
    downloads: 2500000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Xenofell-TorchesEternal-0.2.0.png",
    categories: ["Mods"],
    date_updated: "2026-06-19T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "BoneAppetit",
    full_name: "RockerKitten-BoneAppetit",
    owner: "RockerKitten",
    package_url: "https://thunderstore.io/c/valheim/p/RockerKitten/BoneAppetit/",
    description: "New food and cooking stations!",
    version_number: "3.3.1",
    rating_score: 48,
    downloads: 2300000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/RockerKitten-BoneAppetit-3.3.1.png",
    categories: [
      "Server-side",
      "Client-side",
      "Crafting",
      "Tools",
      "Building",
      "Mistlands Update",
      "Utility",
      "Mods",
    ],
    date_updated: "2026-06-11T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "This_Goes_Here",
    full_name: "ASharpPen-This_Goes_Here",
    owner: "ASharpPen",
    package_url: "https://thunderstore.io/c/valheim/p/ASharpPen/This_Goes_Here/",
    description: "Small mod for mod authors to run file operations in bepinex folders.",
    version_number: "2.1.2",
    rating_score: 18,
    downloads: 2100000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/ASharpPen-This_Goes_Here-2.1.2.png",
    categories: ["Mistlands Update", "Deep North Update"],
    date_updated: "2026-06-03T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "BiggerBoatMapExploreRadius",
    full_name: "nearbear-BiggerBoatMapExploreRadius",
    owner: "nearbear",
    package_url: "https://thunderstore.io/c/valheim/p/nearbear/BiggerBoatMapExploreRadius/",
    description:
      "This is a Bepinex mod for Valheim that increases the exploration radius while in a boat.",
    version_number: "1.0.3",
    rating_score: 47,
    downloads: 1900000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/nearbear-BiggerBoatMapExploreRadius-1.0.3.png",
    categories: ["Mods"],
    date_updated: "2026-05-25T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SmarterContainers",
    full_name: "Roses-SmarterContainers",
    owner: "Roses",
    package_url: "https://thunderstore.io/c/valheim/p/Roses/SmarterContainers/",
    description:
      "Want to quickly drop your loot? Tired of looking for chest with a specific item-stack in order to store some more of it? Teach your containers to arrange items with their neighbor…",
    version_number: "1.7.0",
    rating_score: 27,
    downloads: 1800000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Roses-SmarterContainers-1.7.0.png",
    categories: ["Mods", "Client-side", "Tweaks"],
    date_updated: "2026-05-17T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "BetterNetworking_Valheim",
    full_name: "CW_Jesse-BetterNetworking_Valheim",
    owner: "CW_Jesse",
    package_url: "https://thunderstore.io/c/valheim/p/CW_Jesse/BetterNetworking_Valheim/",
    description:
      "Improve multiplayer performance using compression, queue size, send rate, and other features.",
    version_number: "2.3.2",
    rating_score: 66,
    downloads: 1700000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/CW_Jesse-BetterNetworking_Valheim-2.3.2.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Hildir's Request Update",
      "Tools",
      "Mistlands Update",
      "Utility",
      "Mods",
      "Misc",
      "Libraries",
    ],
    date_updated: "2026-05-08T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Sages_Vault",
    full_name: "Fantu-Sages_Vault",
    owner: "Fantu",
    package_url: "https://thunderstore.io/c/valheim/p/Fantu/Sages_Vault/",
    description:
      "Sages Vault add some elegant clothing for a more civilized age and new Artifacts of incredible power",
    version_number: "1.1.4",
    rating_score: 16,
    downloads: 1600000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Fantu-Sages_Vault-1.1.4.png",
    categories: ["Gear"],
    date_updated: "2026-04-29T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Backpacks",
    full_name: "Smoothbrain-Backpacks",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/Backpacks/",
    description: "Adds a very nice backpack and Build Your Own Backpack™!",
    version_number: "1.3.8",
    rating_score: 107,
    downloads: 1500000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-Backpacks-1.3.8.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Gear",
      "Utility",
      "Mods",
      "Bog Witch Update",
      "Misc",
      "Libraries",
    ],
    date_updated: "2026-04-20T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "MassFarming",
    full_name: "k942-MassFarming",
    owner: "k942",
    package_url: "https://thunderstore.io/c/valheim/p/k942/MassFarming/",
    description: "Xeio's mod to assist with large scale farming in Valheim",
    version_number: "1.11.0",
    rating_score: 46,
    downloads: 1400000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/k942-MassFarming-1.11.0.png",
    categories: ["Mods", "Client-side", "Hildir's Request Update", "Bog Witch Update"],
    date_updated: "2026-04-11T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "MinimalStatusEffects",
    full_name: "RandyKnapp-MinimalStatusEffects",
    owner: "RandyKnapp",
    package_url: "https://thunderstore.io/c/valheim/p/RandyKnapp/MinimalStatusEffects/",
    description:
      "Shrink the status effect list and put it in a vertical list below the minimap. Position and size is customizable.",
    version_number: "1.0.7",
    rating_score: 86,
    downloads: 1300000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/RandyKnapp-MinimalStatusEffects-1.0.7.png",
    categories: [
      "Client-side",
      "Hildir's Request Update",
      "Ashlands Update",
      "Utility",
      "Bog Witch Update",
    ],
    date_updated: "2026-04-02T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Farming",
    full_name: "Smoothbrain-Farming",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/Farming/",
    description:
      "Adds a skill that makes crops grow faster and increases item yield for harvesting crops.",
    version_number: "2.2.2",
    rating_score: 104,
    downloads: 1200000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-Farming-2.2.2.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Bog Witch Update",
      "Mods",
      "Misc",
    ],
    date_updated: "2026-03-24T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Bigger_Chests",
    full_name: "robclancy-Bigger_Chests",
    owner: "robclancy",
    package_url: "https://thunderstore.io/c/valheim/p/robclancy/Bigger_Chests/",
    description:
      "Bigger chests, ship storage and carts to help with the tedious chest spam. New sizes are to help with feeling a little more freedom while hoarding while not being overpowered and…",
    version_number: "1.0.2",
    rating_score: 15,
    downloads: 1100000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/robclancy-Bigger_Chests-1.0.2.png",
    categories: ["Server-side", "Client-side", "Tweaks", "Mistlands Update", "Mods"],
    date_updated: "2026-03-14T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SpeedyPaths",
    full_name: "Nextek-SpeedyPaths",
    owner: "Nextek",
    package_url: "https://thunderstore.io/c/valheim/p/Nextek/SpeedyPaths/",
    description:
      "Gives more purpose to paths. Increases player speed on paths and constructions. Reduces stamina consumed while sprinting on paths. Exposes optional modifiers for regular terrain i…",
    version_number: "1.0.9",
    rating_score: 97,
    downloads: 1000000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Nextek-SpeedyPaths-1.0.9.png",
    categories: [
      "Transportation",
      "Server-side",
      "Client-side",
      "Tweaks",
      "Hildir's Request Update",
      "Ashlands Update",
      "Mistlands Update",
      "Utility",
      "Bog Witch Update",
      "Mods",
    ],
    date_updated: "2026-03-05T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SmoothSave",
    full_name: "Smoothbrain-SmoothSave",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/SmoothSave/",
    description: "Removes the freeze that happens if the world is being saved.",
    version_number: "1.0.5",
    rating_score: 45,
    downloads: 960000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-SmoothSave-1.0.5.png",
    categories: ["Server-side", "Tweaks", "Tools", "Ashlands Update", "Utility", "Mods", "Misc"],
    date_updated: "2026-02-23T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "NoStamCosts",
    full_name: "BasilPanda-NoStamCosts",
    owner: "BasilPanda",
    package_url: "https://thunderstore.io/c/valheim/p/BasilPanda/NoStamCosts/",
    description: "Removes stamina consumption while holding the hammer, hoe, and cultivator!",
    version_number: "0.1.2",
    rating_score: 20,
    downloads: 920000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/BasilPanda-NoStamCosts-0.1.2.png",
    categories: ["Mods"],
    date_updated: "2026-02-13T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "StartupAccelerator",
    full_name: "Smoothbrain-StartupAccelerator",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/StartupAccelerator/",
    description: "Makes mods load faster.",
    version_number: "1.0.3",
    rating_score: 38,
    downloads: 880000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-StartupAccelerator-1.0.3.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2026-02-03T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SmartSkills",
    full_name: "Smoothbrain-SmartSkills",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/SmartSkills/",
    description: "Improves various aspects regarding the skills in the game.",
    version_number: "1.0.2",
    rating_score: 22,
    downloads: 840000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-SmartSkills-1.0.2.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2026-01-24T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "InstantEquip",
    full_name: "Smoothbrain-InstantEquip",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/InstantEquip/",
    description: "Weapons or armor or both can be equipped instantly.",
    version_number: "1.0.6",
    rating_score: 31,
    downloads: 800000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-InstantEquip-1.0.6.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Gear",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2026-01-14T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SailingSpeed",
    full_name: "Smoothbrain-SailingSpeed",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/SailingSpeed/",
    description: "Lets you configure the base speed of ships.",
    version_number: "1.0.3",
    rating_score: 15,
    downloads: 760000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-SailingSpeed-1.0.3.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2026-01-04T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "PlanBuild",
    full_name: "MathiasDecrock-PlanBuild",
    owner: "MathiasDecrock",
    package_url: "https://thunderstore.io/c/valheim/p/MathiasDecrock/PlanBuild/",
    description:
      "PlanBuild enables you to plan, copy and share your building creations in Valheim with ease. Includes terrain tools and immersion items.",
    version_number: "0.19.1",
    rating_score: 137,
    downloads: 720000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/MathiasDecrock-PlanBuild-0.19.1.png",
    categories: [
      "Server-side",
      "Client-side",
      "Hildir's Request Update",
      "Building",
      "Ashlands Update",
      "Mistlands Update",
      "Bog Witch Update",
      "Deep North Update",
      "Mods",
      "AI Generated",
    ],
    date_updated: "2025-12-24T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Server_devcommands",
    full_name: "JereKuusela-Server_devcommands",
    owner: "JereKuusela",
    package_url: "https://thunderstore.io/c/valheim/p/JereKuusela/Server_devcommands/",
    description: "Enables devcommands and utilities for server admins.",
    version_number: "1.115.0",
    rating_score: 112,
    downloads: 680000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/JereKuusela-Server_devcommands-1.115.0.png",
    categories: ["Tools", "Server-side", "Client-side"],
    date_updated: "2025-12-14T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Mining",
    full_name: "Smoothbrain-Mining",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/Mining/",
    description:
      "Adds a skill that increases damage dealt while mining and item yield from ore deposits.",
    version_number: "1.1.6",
    rating_score: 108,
    downloads: 640000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-Mining-1.1.6.png",
    categories: [
      "Server-side",
      "Client-side",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2025-12-03T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "ConversionSizeAndSpeed",
    full_name: "Smoothbrain-ConversionSizeAndSpeed",
    owner: "Smoothbrain",
    package_url: "https://thunderstore.io/c/valheim/p/Smoothbrain/ConversionSizeAndSpeed/",
    description:
      "Lets you configure the input size and conversion speed of building pieces like the smelter, windmill and charcoal kiln.",
    version_number: "1.0.17",
    rating_score: 34,
    downloads: 600000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Smoothbrain-ConversionSizeAndSpeed-1.0.17.png",
    categories: [
      "Server-side",
      "Client-side",
      "Crafting",
      "Tweaks",
      "Tools",
      "Ashlands Update",
      "Utility",
      "Mods",
      "Misc",
    ],
    date_updated: "2025-11-23T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Expand_World",
    full_name: "JereKuusela-Expand_World",
    owner: "JereKuusela",
    package_url: "https://thunderstore.io/c/valheim/p/JereKuusela/Expand_World/",
    description: "Modpack of Expand World mods",
    version_number: "1.56.0",
    rating_score: 23,
    downloads: 2400000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/JereKuusela-Expand_World-1.56.0.png",
    categories: ["Modpacks", "Server-side", "Client-side"],
    date_updated: "2025-11-12T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "ValheimPlus",
    full_name: "ValheimPlus1-ValheimPlus",
    owner: "ValheimPlus1",
    package_url: "https://thunderstore.io/c/valheim/p/ValheimPlus1/ValheimPlus/",
    description: "This is a just a version of Valheim with a few small QOL mods",
    version_number: "1.2.1",
    rating_score: 1,
    downloads: 1900000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/ValheimPlus1-ValheimPlus-1.2.1.png",
    categories: ["Modpacks", "Ashlands Update", "Utility"],
    date_updated: "2025-11-01T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Monstrum_Warfare_Boss_Weapons_Upgrades",
    full_name: "Connor-Monstrum_Warfare_Boss_Weapons_Upgrades",
    owner: "Connor",
    package_url:
      "https://thunderstore.io/c/valheim/p/Connor/Monstrum_Warfare_Boss_Weapons_Upgrades/",
    description:
      "A mod which upgrades Therzie-Monstrum Boss Weapons usable till Ashlands and DeepNorth",
    version_number: "1.2.0",
    rating_score: 1,
    downloads: 890000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Connor-Monstrum_Warfare_Boss_Weapons_Upgrades-1.2.0.png",
    categories: ["Server-side", "Client-side", "Modpacks", "Tweaks", "Gear"],
    date_updated: "2025-10-21T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "SleepyTime",
    full_name: "TeamWhupass-SleepyTime",
    owner: "TeamWhupass",
    package_url: "https://thunderstore.io/c/valheim/p/TeamWhupass/SleepyTime/",
    description:
      "A server mod that loosens the requirement for all players to be in bed before skipping the night. So long as half the players on the server (rounded down) are in bed, you can slee…",
    version_number: "1.1.2",
    rating_score: 0,
    downloads: 410000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/TeamWhupass-SleepyTime-1.1.2.png",
    categories: ["Mods", "Modpacks", "Server-side", "Tweaks"],
    date_updated: "2025-10-10T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "Skillin_It_Softly",
    full_name: "OdinPlus-Skillin_It_Softly",
    owner: "OdinPlus",
    package_url: "https://thunderstore.io/c/valheim/p/OdinPlus/Skillin_It_Softly/",
    description: "A collection of all skill mods made by SmoothBrain.",
    version_number: "1.4.0",
    rating_score: 0,
    downloads: 360000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/OdinPlus-Skillin_It_Softly-1.4.0.png",
    categories: ["Modpacks", "Mistlands Update"],
    date_updated: "2025-09-29T12:00:00.000Z",
    source: "thunderstore",
  },
  {
    name: "AzuQOL",
    full_name: "Azumatt-AzuQOL",
    owner: "Azumatt",
    package_url: "https://thunderstore.io/c/valheim/p/Azumatt/AzuQOL/",
    description:
      "A collection of QOL mods that give life to your game. Some are by me, some are by others.",
    version_number: "2.1.1",
    rating_score: 8,
    downloads: 320000,
    is_deprecated: false,
    icon: "https://ccdn.thunderstore.io/live/repository/icons/Azumatt-AzuQOL-2.1.1.png",
    categories: ["Modpacks"],
    date_updated: "2025-09-18T12:00:00.000Z",
    source: "thunderstore",
  },
];

/**
 * Icons come from Thunderstore's CDN. The `ccdn`/`gcdn` hosts are unreachable
 * on some networks and from CI; the backup CDN serves the same files, so the
 * fixtures point there instead of rendering placeholders.
 */
export const PACKAGES: ThunderstorePackage[] = PACKAGES_RAW.map((pkg) => ({
  ...pkg,
  icon: pkg.icon.replace("ccdn.thunderstore.io", "hcdn-1.hcdn.thunderstore.io"),
}));
