/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBrowseRouteImport } from './routes/_app.browse'
import { Route as AppCompatibilityRouteImport } from './routes/_app.compatibility'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppInstalledRouteImport } from './routes/_app.installed'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppModpacksRouteImport } from './routes/_app.modpacks'
import { Route as AppProfilesRouteImport } from './routes/_app.profiles'
import { Route as AppSavesRouteImport } from './routes/_app.saves'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppCompatibilityRoute = AppCompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppInstalledRoute = AppInstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppModpacksRoute = AppModpacksRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppSavesRoute = AppSavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof AppBrowseRoute
  '/compatibility': typeof AppCompatibilityRoute
  '/config': typeof AppConfigRoute
  '/installed': typeof AppInstalledRoute
  '/logs': typeof AppLogsRoute
  '/modpacks': typeof AppModpacksRoute
  '/profiles': typeof AppProfilesRoute
  '/saves': typeof AppSavesRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof AppBrowseRoute
  '/compatibility': typeof AppCompatibilityRoute
  '/config': typeof AppConfigRoute
  '/installed': typeof AppInstalledRoute
  '/logs': typeof AppLogsRoute
  '/modpacks': typeof AppModpacksRoute
  '/profiles': typeof AppProfilesRoute
  '/saves': typeof AppSavesRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/browse': typeof AppBrowseRoute
  '/_app/compatibility': typeof AppCompatibilityRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/installed': typeof AppInstalledRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/modpacks': typeof AppModpacksRoute
  '/_app/profiles': typeof AppProfilesRoute
  '/_app/saves': typeof AppSavesRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/compatibility'
    | '/config'
    | '/installed'
    | '/logs'
    | '/modpacks'
    | '/profiles'
    | '/saves'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/compatibility'
    | '/config'
    | '/installed'
    | '/logs'
    | '/modpacks'
    | '/profiles'
    | '/saves'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/browse'
    | '/_app/compatibility'
    | '/_app/config'
    | '/_app/installed'
    | '/_app/logs'
    | '/_app/modpacks'
    | '/_app/profiles'
    | '/_app/saves'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compatibility': {
      id: '/_app/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof AppCompatibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installed': {
      id: '/_app/installed'
      path: '/installed'
      fullPath: '/installed'
      preLoaderRoute: typeof AppInstalledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modpacks': {
      id: '/_app/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof AppModpacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles': {
      id: '/_app/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saves': {
      id: '/_app/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof AppSavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrowseRoute: typeof AppBrowseRoute
  AppCompatibilityRoute: typeof AppCompatibilityRoute
  AppConfigRoute: typeof AppConfigRoute
  AppInstalledRoute: typeof AppInstalledRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModpacksRoute: typeof AppModpacksRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppSavesRoute: typeof AppSavesRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseRoute: AppBrowseRoute,
  AppCompatibilityRoute: AppCompatibilityRoute,
  AppConfigRoute: AppConfigRoute,
  AppInstalledRoute: AppInstalledRoute,
  AppLogsRoute: AppLogsRoute,
  AppModpacksRoute: AppModpacksRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppSavesRoute: AppSavesRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
